# -*- coding: utf-8 -*-
{
    'name': "Control de Moldes",
    'summary': """""",
    'description': """""",
    'author': "POK",
    'website': "http://www.pok.com",
    'category': 'Uncategorized',
    'version': '14.0.0.0.1',
    'depends': ['base', 'contacts', 'repair', 'stock', 'website'],
    'data': [
        #'data/data.xml',
	    'data/ir_cron_data.xml',
	    'data/ir_sequence_data.xml',
	    'data/mail_template_data.xml',
	    'data/model.category.csv',
	    'data/model_category_data.xml',
	    'security/mold_control_security.xml',
	    'security/ir.model.access.csv',
	    'report/mold_report.xml',
	    'wizard/wizard_change_acceptable_views.xml',
	    'views/mold_attachment_views.xml',
	    'views/mold_control_views.xml',
	    'views/mold_request_views.xml',
	    'views/mold_revision_views.xml',
	    'views/mold_request_stage_views.xml',
	    'views/mold_tag_views.xml',
	    'views/new_table_views.xml',
	    'views/model_category_views.xml',
	    'views/inherited_repair_order_views.xml',
	    'views/inherited_res_partner_views.xml',
	    'views/template.xml',
    ],
}
